[package]
name = "CMV"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdb_mi = "0.1.3"
read-process-memory = "0.1.6"
